<?php
$data = array (
  0 => 
  array (
    'cat_id' => '10',
    'cat_name' => '汽车服务',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '汽车服务',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '7',
    'aricle_num' => '7',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '12',
    'cat_name' => '保险学院',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '保险学院',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '0',
    'has_children' => '9',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '22',
    'cat_name' => '理赔服务',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '理赔服务',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '关于中联',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '关于中联',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '8',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '新闻中心',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '新闻中心',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '4',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  7 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  8 => 
  array (
    'cat_id' => '6',
    'cat_name' => '中联新闻',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '中联新闻',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '5',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  9 => 
  array (
    'cat_id' => '7',
    'cat_name' => '行业动态',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '行业动态',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '5',
    'has_children' => '0',
    'aricle_num' => '24',
  ),
  10 => 
  array (
    'cat_id' => '8',
    'cat_name' => '监管动态',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '监管动态',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '5',
    'has_children' => '0',
    'aricle_num' => '13',
  ),
  11 => 
  array (
    'cat_id' => '9',
    'cat_name' => '其他新闻',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '其他新闻',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '5',
    'has_children' => '0',
    'aricle_num' => '21',
  ),
  12 => 
  array (
    'cat_id' => '11',
    'cat_name' => '服务网点',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '服务网点',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  13 => 
  array (
    'cat_id' => '19',
    'cat_name' => '家财',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '家财',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  14 => 
  array (
    'cat_id' => '20',
    'cat_name' => '养老',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  15 => 
  array (
    'cat_id' => '21',
    'cat_name' => '教育',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '教育',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  16 => 
  array (
    'cat_id' => '13',
    'cat_name' => '保险基础知识',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '保险基础知识',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  17 => 
  array (
    'cat_id' => '14',
    'cat_name' => '保险规划',
    'cat_type' => '1',
    'keywords' => '公司动态',
    'cat_desc' => '保险规划',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  18 => 
  array (
    'cat_id' => '15',
    'cat_name' => '保险词条',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '保险词条',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '14',
  ),
  19 => 
  array (
    'cat_id' => '16',
    'cat_name' => '车险专区',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '车险专区',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '8',
  ),
  20 => 
  array (
    'cat_id' => '17',
    'cat_name' => '旅游',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '旅游',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  21 => 
  array (
    'cat_id' => '18',
    'cat_name' => '医疗',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '医疗',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '12',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  22 => 
  array (
    'cat_id' => '23',
    'cat_name' => '车险理赔',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '车险理赔',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '22',
    'has_children' => '4',
    'aricle_num' => '4',
  ),
  23 => 
  array (
    'cat_id' => '24',
    'cat_name' => '非车险理赔',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '非车险理赔',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '22',
    'has_children' => '6',
    'aricle_num' => '6',
  ),
  24 => 
  array (
    'cat_id' => '25',
    'cat_name' => '理赔案例',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '理赔案例',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '23',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  25 => 
  array (
    'cat_id' => '26',
    'cat_name' => '下载专区',
    'cat_type' => '1',
    'keywords' => '下载专区',
    'cat_desc' => '下载专区',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '23',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  26 => 
  array (
    'cat_id' => '29',
    'cat_name' => '线上报案',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '线上报案',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '24',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '理赔案例',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '理赔案例',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '24',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '下载专区',
    'cat_type' => '1',
    'keywords' => '中联保险经纪      中联保险   车险  汽车保险  长沙车险  湖南车险   湖南保险',
    'cat_desc' => '下载专区1',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '24',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
);
?>